name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 # Explicitly use Ubuntu 22.04 to avoid issues with ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Ensure this version matches your project's Node.js requirements

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install

    - name: Build project
      run: |
        echo "Building project..."
        npm run build

    - name: Verify Build Directory
      run: |
        echo "Checking if the dist directory exists..."
        ls -la dist # Verify that the 'dist' directory is created after the build process

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
